# generated by gemini
from http.server import BaseHTTPRequestHandler, HTTPServer
import json
import io
import contextlib
import traceback

class CodeHandler(BaseHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        
        try:
            data = json.loads(post_data.decode('utf-8'))
            code_to_run = data.get('code', '')
            
            output_buffer = io.StringIO()
            
            try:
                with contextlib.redirect_stdout(output_buffer):
                    exec(code_to_run, {})
                
                result = output_buffer.getvalue()
                status = 200
                response = {"output": result, "error": ""}
                
            except Exception as e:
                status = 400
                response = {"output": "", "error": str(e)}

        except json.JSONDecodeError:
            status = 400
            response = {"output": "", "error": "Invalid JSON"}

        self.send_response(status)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps(response).encode('utf-8'))

def run(server_class=HTTPServer, handler_class=CodeHandler, port=8080):
    server_address = ('', port)
    print(f"Worker shim started on port {port}...")
    httpd = server_class(server_address, handler_class)
    httpd.serve_forever()

if __name__ == "__main__":
    run()